// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTgAJRMcc3h8Cisd6XHbuyEp5kOcyvOfM',
    appId: '1:707145385701:android:a05900fbeb08c5de38360c',
    messagingSenderId: '707145385701',
    projectId: 'solvexo-cec1a',
    storageBucket: 'solvexo-cec1a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8SBN_Z7No0yeqhzy1qzxJlQ9DpANVGfc',
    appId: '1:707145385701:ios:77cd62c6f6a4c6b138360c',
    messagingSenderId: '707145385701',
    projectId: 'solvexo-cec1a',
    storageBucket: 'solvexo-cec1a.firebasestorage.app',
    androidClientId: '707145385701-fd2nfbjmhln0at4iadcu5j0s1g4rjf01.apps.googleusercontent.com',
    iosClientId: '707145385701-7b85837kd77cebhf80gfa6f8puboaosn.apps.googleusercontent.com',
    iosBundleId: 'com.solvexo.solvexoPos',
  );
}
